### ISSUE TITLE
Conditional Git config is not used

### ISSUE THREAD

**Issue by Weltraumschaf** [xwmx/nb#198] opened 2022-09-23 11:32 UTC
I have a conditional config for my git identities in my [dotfiles](https://github.com/Weltraumschaf/dotfiles/blob/master/src/dotfiles/_gitconfig#L5):

```
[includeIf "gitdir:~/nb/"]
  path = ~/.gitconfig_private
```

When I start nb it asks me for a name and email and adds them as global Git options:

```
[user]
	name = Sven
	email = foo@bar.com
```

Since I assume that the git repository nb operates is in `~/nb/` on macOS I expect that nb uses the identity option set by the `includeIf` in my Git config.

**Comment by xwmx** [comment] 2022-09-24 06:49
Thanks for the info. I’ll have to investigate this more. I’m still trying to get `includeIf` to work consistently in tests. The default directory for `nb` is `~/.nb` (with a leading `.`).

**Comment by Weltraumschaf** [comment] 2022-09-28 08:42
> The default directory for `nb` is `~/.nb` (with a leading `.`)

Sorry, that's a typo. I did the test with right path and introduced the typo for the write up here. I double checked now: Also with the right path `~/.nb` it does not work.

**Comment by ahmedelgabri** [comment] 2024-10-23 12:15
I have the same issue but I store my git config inside `$XDG_CONFIG_HOME/git/config` which is already supported by git https://git-scm.com/docs/git-config#Documentation/git-config.txt---global 

`git config --list user.name` and `git config --list user.name` work as expected but `nb` will write to `~/.gitconfig`

**Comment by xwmx** [comment] 2024-10-24 01:57
@ahmedelgabri Does `nb` recognize your email and username when there is no `~/.gitconfig` file, or does it prompt you for it?

This git configuration seems to be contained in the [`_git_required()`](https://github.com/xwmx/nb/blob/master/nb#L3836) function. This function reads the values with `git config --global --includes user.name` and `git config --global --includes user.email`. If they are missing, the user is prompted for the values which are then set with `git config --global user.name "${__name}"` and `git config --global user.email "${__email}"`. According to the documentation for [`git config --global`](https://git-scm.com/docs/git-config#Documentation/git-config.txt---global), it writes "to `$XDG_CONFIG_HOME/git/config` file if this file exists and the `~/.gitconfig` file doesn’t."

So far I only see `nb` updating the git config with these particular commands. Let me know if you have any additional information that could help me identify the issue.

**Comment by ahmedelgabri** [comment] 2024-10-24 05:45
@xwmx if it would recognize them, why would it prompt me to set them? And why would it set it in `~/.gitconfig`?

**Comment by xwmx** [comment] 2024-10-24 06:48
@ahmedelgabri If the name and email are configured in `$XDG_CONFIG_HOME/git/config`, then there is no technical reason I'm aware of that `nb` would prompt you for them or write them in `~/.gitconfig` since the commands use [`git config --global`](https://git-scm.com/docs/git-config#Documentation/git-config.txt---global) which reads from and writes "to `$XDG_CONFIG_HOME/git/config` file if this file exists and the `~/.gitconfig` file doesn’t." I just checked manually on a VM and confirmed that the `git config --global` commands in `nb` read from and write to `$XDG_CONFIG_HOME/git/config` without creating `~/.gitconfig` as long as `$XDG_CONFIG_HOME/git/config` is present.

If a pre-existing `~/.gitconfig` file is already present, then `git config --global` gives `~/.gitconfig` precedence and will read from and write to `~/.gitconfig` instead of `$XDG_CONFIG_HOME/git/config`.

The only case that I can see where `git config --global` creates a `~/.gitconfig` is if `$XDG_CONFIG_HOME/git/config` is not present.

**Comment by ahmedelgabri** [comment] 2024-10-24 08:42
@xwmx you are totally right, found out a `~/.gitconfig` file that was created by another tool and that's why it didn't work as expected. Removed the file and everything works as expected now.

**Comment by xwmx** [comment] 2024-10-24 22:23
@ahmedelgabri Awesome. Glad it's working.

**Comment by xwmx** [comment] 2024-10-24 22:28
@felixdv I'm just catching up to this now. I added [a test covering `IncludeIf` with `hasconfig:remote`](https://github.com/xwmx/nb/blob/4c2cadad33c4fd703c48d1c5f0fc472f3708ff7c/test/git.bats#L202) and it appears to be working as intended at this time. If you are still encountering this issue, please let me know!

**Comment by xwmx** [comment] 2024-10-25 22:21
Tests are passing for this and everything seems to be working, so I'm going to close this. Please let me know if there are any more issues with this. Thanks!

**Closed by xwmx** 2024-10-25 22:21 UTC
